### ISSUE TITLE
Error on routing on Sylius 1.12

### ISSUE THREAD

**Issue by SquareInnov** [Setono/SyliusVariantLinkPlugin#49]
While trying to use this Plugin, I encountered this error on routing : 
"The controller for URI "/fr_FR/products/{slug}/{variant}" is not callable: Controller "sylius.controller.product:showAction" does neither exist as service nor as class."
I solved it by editing the routing file like this : #48

**Comment by loevgaard** [comment]
Fixed in https://github.com/Setono/SyliusVariantLinkPlugin/pull/48
